server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      # to always initialize the database schema on startup
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    # on shutdown de-register service from eureka server, but it is not recommended to use it in production, because it can cause issues with load balancer and service discovery
    shutdown:
      access: unrestricted
  # info
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


eureka:
  instance:
    # to register service with IP address instead of hostname, useful in docker environment. Hostname is used with DNS mapping.
    preferIpAddress: true
  client:
    fetchRegistry: true # to fetch registry from eureka server
    registerWithEureka: true # to register this service in eureka server
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        # Set the logging level for the "com.eazybytes" package to DEBUG. This means that all log messages at the DEBUG level and above (INFO, WARN, ERROR) will be logged for classes in this package.
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1