spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  # tell gateway to use service discovery to find routes
  cloud:
    gateway:
      discovery:
        locator:
          # When disabled, Spring Cloud Gateway will not automatically create routes based on service discovery.
          # You will need to manually define routes in your configuration for each service you want to route to.
          enabled: false
          # By default, Spring Cloud Gateway uses the service ID as the route ID and the path prefix for the route. Setting lowerCaseServiceId to true will convert the service ID to lowercase before using it as the route ID and path prefix.
          # This can be useful if your service IDs are in uppercase and you want to ensure that the routes are defined in lowercase for consistency.
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        # Set the logging level for the "com.eazybytes" package to DEBUG. This means that all log messages at the DEBUG level and above (INFO, WARN, ERROR) will be logged for classes in this package.
        gatewayserver: DEBUG

